version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      db_net:
        ipv4_address: 172.15.1.14

  db:
    image: postgres:15-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db:/db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=papa
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=audience
    networks:
      db_net:
        ipv4_address: 172.15.1.4

networks:
  db_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.1.0/24
